<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-799KKK6" failures="1" tests="2" name="testrunners.TestRunner1" time="5.323" errors="0" timestamp="2024-07-14T22:16:12 IST" skipped="0">
  <testcase classname="testrunners.TestRunner1" name="runScenario" time="2.992"/>
  <testcase classname="testrunners.TestRunner1" name="runScenario" time="2.331">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stefdef.Test1.data_validated2(Test1.java:40)
at âœ½.data validated2(file:///C:/Users/QJspiders/eclipse-workspace/Selenium/cucumber_testng_01/./src/test/resources/features/Test.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testrunners.TestRunner1 -->
